Controllers/CollectionController.cs
using Collections.Data;
using Collections.Interfaces;
using Collections.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Collections.Controllers
{
    public class CollectionController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IPhotoService _photoService;
        public CollectionController(ApplicationDbContext db, IPhotoService photoService)
        {
            _db = db;
            _photoService = photoService;
        }
        public IActionResult Index(string id)
        {
            if(User.IsInRole("admin"))
            {
                if (id != null)
                {
                    GlobalAppUserId.UserId = id;
                }
            }
            var objCollectionsList = _db.Collections.Where(x => x.UserCollectionId == GlobalAppUserId.UserId);
            return View(objCollectionsList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateCollectionViewModel collectionVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(collectionVM.Image);
                var collection = new Collection
                {
                    Name = collectionVM.Name,
                    Description = collectionVM.Description,
                    Theme = collectionVM.Theme,
                    UserCollectionId = GlobalAppUserId.UserId,
                    FieldName = collectionVM.FieldName,
                    FieldName1 = collectionVM.FieldName1,
                    FieldName2 = collectionVM.FieldName2,
                    TypeField = collectionVM.TypeField,
                    TypeField1 = collectionVM.TypeField1,
                    TypeField2 = collectionVM.TypeField2
                };
                if (collectionVM.Image != null) 
                    collection.Image = result.Url.ToString();
                _db.Collections.Add(collection);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var collectionFromDb = _db.Collections.Find(id);
            return View(collectionFromDb);
        }
        [HttpPost]
        public IActionResult Edit(string Name, string Description, CollectionTheme Theme, int id)
        {
            if (ModelState.IsValid)
            {
                var item = _db.Collections.Find(id);
                item.Name = Name;
                item.Description = Description;
                item.Theme = Theme;
                item.UserCollectionId = GlobalAppUserId.UserId;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Del(int id)
        {
            var collectionFromDb = _db.Collections.Find(id);
            return View(collectionFromDb);
        }
        [HttpPost]
        public IActionResult Del(Collection obj)
        {
            _db.Collections.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/SearchController.cs
using Collections.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Collections.Controllers
{
    public class SearchController : Controller
    {
        private readonly ApplicationDbContext _db;
        public SearchController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index(string searchString)
        {
            var items = _db.Items.Where(s => s.Name.Contains(searchString));
            var collections = _db.Collections.Where(s => s.Name.Contains(searchString) || s.Description.Contains(searchString));
            foreach (var obj in collections)
            {
                var collectionItems = _db.Items.Where(x => x.CollectionId == obj.Id);
                items = items.Concat(collectionItems).Distinct().OrderBy(x => x.Name);
            }
            return View(await items.ToListAsync());
        }
    }
}

Controllers/UserController.cs
using Collections.Data;
using Collections.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Collections.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly ApplicationDbContext _db;
        public UserController(UserManager<AppUser> userManager, ApplicationDbContext db)
        {
            _db = db;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var objAppUserList = _db.AppUsers;
            return View(objAppUserList);
        }

        public async Task<IActionResult> AppointAdmin(string id)
        {
            var user = _db.AppUsers.Find(id);
            user.UserRole = "admin";
            await _userManager.RemoveFromRoleAsync(user, UserRoles.User);
            await _userManager.AddToRoleAsync(user, UserRoles.Admin);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> AppointUser(string id)
        {
            var user = _db.AppUsers.Find(id);
            user.UserRole = "user";
            await _userManager.RemoveFromRoleAsync(user, UserRoles.Admin);
            await _userManager.AddToRoleAsync(user, UserRoles.User);
            return RedirectToAction("Index");
        }

        public IActionResult Block(string id)
        {
            var user = _db.AppUsers.Find(id);
            user.Status = Status.Blocked;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Unblock(string id)
        {
            var user = _db.AppUsers.Find(id);
            user.Status = Status.Active;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Del(string id)
        {
            var appuserFromDb = _db.AppUsers.Find(id);
            return View(appuserFromDb);
        }
        [HttpPost]
        public IActionResult Del(AppUser obj)
        {
            var user = _db.AppUsers.Find(obj.Id);
            _db.AppUsers.Remove(user);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Collections</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Collections.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">All collections</a>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav col-md-auto">
                        @if (User.Identity.IsAuthenticated && !User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Collection" asp-action="Index">My collections</a>
                                <span class="visually-hidden">(current)</span>
                            </li>
                        }
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="User" asp-action="Index">All users</a>
                                <span class="visually-hidden">(current)</span>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav ms-md-auto">
                        <form asp-controller="Search" asp-action="Index" class="d-flex">
                            <input class="form-control me-sm-2" type="text" name="searchString" placeholder="Search">
                            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                        </form>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link active" title="Manage">Hello @User.Identity.Name!</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                <span class="visually-hidden">(current)</span>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                <span class="visually-hidden">(current)</span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                <span class="visually-hidden">(current)</span>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>