Models/Item.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Collections.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Tag { get; set; }

        public int? SpecialInt { get; set; }
        public int? SpecialInt1 { get; set; }
        public int? SpecialInt2 { get; set; }
        public string? SpecialString { get; set; }
        public string? SpecialString1 { get; set; }
        public string? SpecialString2 { get; set; }
        public string? SpecialText { get; set; }
        public string? SpecialText1 { get; set; }
        public string? SpecialText2 { get; set; }
        public DateTime? SpecialDataType { get; set; }
        public DateTime? SpecialDataType1 { get; set; }
        public DateTime? SpecialDataType2 { get; set; }
        public bool? SpecialBool { get; set; }
        public bool? SpecialBool1 { get; set; }
        public bool? SpecialBool2 { get; set; }

        [ForeignKey("CollectionItem")]
        [Required]
        public int CollectionId { get; set; }
        public virtual Collection CollectionItem { get; set; }
        [ForeignKey("UserItem")]
        [Required]
        public string UserId { get; set; }
        public virtual AppUser UserItem { get; set; }

        public virtual List<Comment> Comments { get; set; } = new List<Comment>();
    }
    public enum SortState
    {
        NameAsc,
        NameDesc,
        TagAsc,
        TagDesc,
    }
    public static class GlobalItemId
    {
        public static int ItemId { get; set; }
    }
}

Controllers/CollectionController.cs
using Collections.Data;
using Collections.Interfaces;
using Collections.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Collections.Controllers
{
    public class CollectionController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IPhotoService _photoService;
        public CollectionController(ApplicationDbContext db, IPhotoService photoService)
        {
            _db = db;
            _photoService = photoService;
        }
        public IActionResult Index(string id)
        {
            if(User.IsInRole("admin"))
            {
                if (id != null)
                {
                    GlobalAppUserId.UserId = id;
                }
            }
            var objCollectionsList = _db.Collections.Where(x => x.UserCollectionId == GlobalAppUserId.UserId);
            return View(objCollectionsList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateCollectionViewModel collectionVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(collectionVM.Image);
                var collection = new Collection
                {
                    Name = collectionVM.Name,
                    Description = collectionVM.Description,
                    Theme = collectionVM.Theme,
                    UserCollectionId = GlobalAppUserId.UserId,
                    FieldName = collectionVM.FieldName,
                    FieldName1 = collectionVM.FieldName1,
                    FieldName2 = collectionVM.FieldName2,
                    TypeField = collectionVM.TypeField,
                    TypeField1 = collectionVM.TypeField1,
                    TypeField2 = collectionVM.TypeField2
                };
                if (collectionVM.Image != null) 
                    collection.Image = result.Url.ToString();
                _db.Collections.Add(collection);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var collectionFromDb = _db.Collections.Find(id);
            return View(collectionFromDb);
        }
        [HttpPost]
        public IActionResult Edit(string Name, string Description, CollectionTheme Theme, int id)
        {
            if (ModelState.IsValid)
            {
                var item = _db.Collections.Find(id);
                item.Name = Name;
                item.Description = Description;
                item.Theme = Theme;
                item.UserCollectionId = GlobalAppUserId.UserId;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Del(int id)
        {
            var collectionFromDb = _db.Collections.Find(id);
            return View(collectionFromDb);
        }
        [HttpPost]
        public IActionResult Del(Collection obj)
        {
            _db.Collections.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/CommentController.cs
using Collections.Data;
using Collections.Models;
using Microsoft.AspNetCore.Mvc;

namespace Collections.Controllers
{
    public class CommentController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CommentController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index(int id)
        {
            if (id != 0)
            {
                GlobalItemId.ItemId = id;
            }
            var objCommentList = _db.Comments.Where(x => x.ItemId == GlobalItemId.ItemId);
            return View(objCommentList);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(string Text)
        {
            if (ModelState.IsValid)
            {
                _db.Comments.Add(new Comment { Text = Text, ItemId = GlobalItemId.ItemId, UserId = GlobalAppUserId.UserId });
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Del(int id)
        {
            var commentFromDb = _db.Comments.Find(id);
            return View(commentFromDb);
        }
        [HttpPost]
        public IActionResult Del(Comment obj)
        {
            _db.Comments.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/ItemController.cs
using Collections.Data;
using Collections.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Collections.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ItemController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index(int id, string tag, string name, string UserId, SortState sortOrder = SortState.NameAsc)
        {
            var items = _db.Items.Where(x => x.CollectionId == id);
            if (UserId != null)
            {
                GlobalAppUserId.UserId2 = UserId;
            }

            if (tag != null && name != null)
            {
                items = items.Where(s => s.Name.Contains(name) && s.Tag.Contains(tag));
                return View(items);
            }
            else
            {
                ViewData["NameSort"] = sortOrder == SortState.NameAsc ? SortState.NameDesc : SortState.NameAsc;
                ViewData["TagSort"] = sortOrder == SortState.TagAsc ? SortState.TagDesc : SortState.TagAsc;
                items = sortOrder switch
                {
                    SortState.NameDesc => items.OrderByDescending(s => s.Name),
                    SortState.TagAsc => items.OrderBy(s => s.Tag),
                    SortState.TagDesc => items.OrderByDescending(s => s.Tag),
                    _ => items.OrderBy(s => s.Name),
                };

                GlobalCollection.CollectionId = id;
                var field = _db.Collections.Find(GlobalCollection.CollectionId);
                GlobalCollection.FieldName = field.FieldName;
                GlobalCollection.TypeField = field.TypeField;
                GlobalCollection.FieldName1 = field.FieldName1;
                GlobalCollection.TypeField1 = field.TypeField1;
                GlobalCollection.FieldName2 = field.FieldName2;
                GlobalCollection.TypeField2 = field.TypeField2;

                return View(await items.AsNoTracking().ToListAsync());
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(string Name, string Tag, int? SpecialInt, int? SpecialInt1, 
            int? SpecialInt2, string? SpecialString, string? SpecialString1, string? SpecialString2, 
            string? SpecialText, string? SpecialText1, string? SpecialText2, DateTime? SpecialDataType, 
            DateTime? SpecialDataType1, DateTime? SpecialDataType2, bool? SpecialBool, bool? SpecialBool1, 
            bool? SpecialBool2)
        {
            if (ModelState.IsValid)
            {
                _db.Items.Add(new Item { Name = Name, Tag = Tag, CollectionId = GlobalCollection.CollectionId, UserId = GlobalAppUserId.UserId,
                    SpecialInt = SpecialInt, SpecialInt1 = SpecialInt1, SpecialInt2 = SpecialInt2, 
                    SpecialString = SpecialString, SpecialString1 = SpecialString1, SpecialString2 = SpecialString2,
                    SpecialText = SpecialText, SpecialText1 = SpecialText1, SpecialText2 = SpecialText2,
                    SpecialDataType = SpecialDataType, SpecialDataType1 = SpecialDataType1, SpecialDataType2 = SpecialDataType2,
                    SpecialBool = SpecialBool, SpecialBool1 = SpecialBool1, SpecialBool2 = SpecialBool2});
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = GlobalCollection.CollectionId });
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var itemFromDb = _db.Items.Find(id);
            return View(itemFromDb);
        }
        [HttpPost]
        public IActionResult Edit(string Name, string Tag, int id, int? SpecialInt, int? SpecialInt1,
            int? SpecialInt2, string? SpecialString, string? SpecialString1, string? SpecialString2,
            string? SpecialText, string? SpecialText1, string? SpecialText2, DateTime? SpecialDataType,
            DateTime? SpecialDataType1, DateTime? SpecialDataType2, bool? SpecialBool, bool? SpecialBool1,
            bool? SpecialBool2)
        {
            if (ModelState.IsValid)
            {
                var item = _db.Items.Find(id);
                item.Name = Name;
                item.Tag = Tag;
                item.SpecialInt = SpecialInt;
                item.SpecialInt1 = SpecialInt1;
                item.SpecialInt2 = SpecialInt2;
                item.SpecialString = SpecialString;
                item.SpecialString1 = SpecialString1;
                item.SpecialString2 = SpecialString2;
                item.SpecialText = SpecialText;
                item.SpecialText1 = SpecialText1;
                item.SpecialText2 = SpecialText2;
                item.SpecialDataType = SpecialDataType;
                item.SpecialDataType1 = SpecialDataType1;
                item.SpecialDataType2 = SpecialDataType2;
                item.SpecialBool = SpecialBool;
                item.SpecialBool1 = SpecialBool1;
                item.SpecialBool2 = SpecialBool2;
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = GlobalCollection.CollectionId });
            }
            return View();
        }

        [HttpGet]
        public IActionResult Del(int id)
        {
            var itemFromDb = _db.Items.Find(id);
            return View(itemFromDb);
        }
        [HttpPost]
        public IActionResult Del(Item obj)
        {
            _db.Items.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index", new { id = GlobalCollection.CollectionId });
        }
    }
}

Views/Item/Create.cshtml
@model Item

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="nav-item">Create item</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Tag"></label>
            <input asp-for="Tag" id="productName" class="form-control" />
        </div>
        @if (GlobalCollection.FieldName != null && GlobalCollection.TypeField != null)
        {
            switch (GlobalCollection.TypeField)
                {
                    case FieldType.Numeric:
                        <div class="mb-3">
                            <label asp-for="SpecialInt">@GlobalCollection.FieldName</label>
                            <input asp-for="SpecialInt" type="number" class="form-control" />
                        </div>
                        break;
                    case FieldType.String:
                        <div class="mb-3">
                            <label asp-for="SpecialString">@GlobalCollection.FieldName</label>
                            <input asp-for="SpecialString" class="form-control" />
                        </div>
                        break;
                    case FieldType.Text:
                        <div class="mb-3">
                            <label asp-for="SpecialText">@GlobalCollection.FieldName</label>
                            <input asp-for="SpecialText" class="form-control" />
                        </div>
                        break;
                    case FieldType.Date:
                        <div class="mb-3">
                            <div class="form-group">
                                <label asp-for="SpecialDataType" class="control-label">@GlobalCollection.FieldName</label>
                                <input asp-for="SpecialDataType" class="form-control" />
                                <span asp-validation-for="SpecialDataType" class="text-danger"></span>
                            </div>
                        </div>
                        break;
                    case FieldType.TrueFalse:
                        <div class="mb-3">
                            <span>@GlobalCollection.FieldName</span>
                            <input checked="checked" name="SpecialBool" type="checkbox" value="true" />
                            <input name="SpecialBool" type="hidden" value="false" />
                        </div>
                        break;
                }
        }
        @if (GlobalCollection.FieldName1 != null && GlobalCollection.TypeField1 != null)
        {
            switch (GlobalCollection.TypeField1)
                {
                    case FieldType.Numeric:
                        <div class="mb-3">
                            <label asp-for="SpecialInt1">@GlobalCollection.FieldName1</label>
                            <input asp-for="SpecialInt1" type="number" class="form-control" />
                        </div>
                        break;
                    case FieldType.String:
                        <div class="mb-3">
                            <label asp-for="SpecialString1">@GlobalCollection.FieldName1</label>
                            <input asp-for="SpecialString1" class="form-control" />
                        </div>
                        break;
                    case FieldType.Text:
                        <div class="mb-3">
                            <label asp-for="SpecialText1">@GlobalCollection.FieldName1</label>
                            <input asp-for="SpecialText1" class="form-control" />
                        </div>
                        break;
                    case FieldType.Date:
                        <div class="mb-3">
                            <div class="form-group">
                                <label asp-for="SpecialDataType1" class="control-label">@GlobalCollection.FieldName1</label>
                                <input asp-for="SpecialDataType1" class="form-control" />
                                <span asp-validation-for="SpecialDataType" class="text-danger"></span>
                            </div>
                        </div>
                        break;
                    case FieldType.TrueFalse:
                        <div class="mb-3">
                            <span>@GlobalCollection.FieldName1</span>
                            <input checked="checked" name="SpecialBool1" type="checkbox" value="true" />
                            <input name="SpecialBool1" type="hidden" value="false" />
                        </div>
                        break;
                }
        }
        @if (GlobalCollection.FieldName2 != null && GlobalCollection.TypeField2 != null)
        {
            switch (GlobalCollection.TypeField2)
                {
                    case FieldType.Numeric:
                        <div class="mb-3">
                            <label asp-for="SpecialInt2">@GlobalCollection.FieldName2</label>
                            <input asp-for="SpecialInt2" type="number" class="form-control" />
                        </div>
                        break;
                    case FieldType.String:
                        <div class="mb-3">
                            <label asp-for="SpecialString2">@GlobalCollection.FieldName2</label>
                            <input asp-for="SpecialString2" class="form-control" />
                        </div>
                        break;
                    case FieldType.Text:
                        <div class="mb-3">
                            <label asp-for="SpecialText2">@GlobalCollection.FieldName2</label>
                            <input asp-for="SpecialText2" class="form-control" />
                        </div>
                        break;
                    case FieldType.Date:
                        <div class="mb-3">
                            <div class="form-group">
                                <label asp-for="SpecialDataType2" class="control-label">@GlobalCollection.FieldName2</label>
                                <input asp-for="SpecialDataType2" class="form-control" />
                                <span asp-validation-for="SpecialDataType2" class="text-danger"></span>
                            </div>
                        </div>
                        break;
                    case FieldType.TrueFalse:
                        <div class="mb-3">
                            <span>@GlobalCollection.FieldName2</span>
                            <input checked="checked" name="SpecialBool2" type="checkbox" value="true" />
                            <input name="SpecialBool2" type="hidden" value="false" />
                        </div>
                        break;
                }
        }
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        
        <a asp-controller="Item" asp-action="Index" asp-route-id="@GlobalCollection.CollectionId" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

Views/Item/Del.cshtml
@model Item

<form method="post" asp-action="Del">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="nav-item">Do you want to delete the collection?</h2>
            <hr />
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Item" asp-action="Index" asp-route-id="@GlobalCollection.CollectionId" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

Views/Item/Index.cshtml
@model IEnumerable<Item>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="nav-item">List of item</h2>
        </div>
        @if (GlobalAppUserId.UserId1 == GlobalAppUserId.UserId2 || User.IsInRole("admin"))
        {
            <div class="col-6 text-end">
                <a asp-controller="Item" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus"></i> &nbsp; Create new item
                </a>
            </div>
            <div class="col-12 text-end">
                <a asp-controller="Collection" asp-action="Index" asp-route-id="@GlobalAppUserId.UserId" class="btn btn-primary">Go to my collections</a>
            </div>
            }
        @if (!User.IsInRole("admin"))
        {
            @if (!User.Identity.IsAuthenticated || GlobalAppUserId.UserId1 != GlobalAppUserId.UserId2)
            {
                <div class="col-12 text-end">
                    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Back</a>
                </div>
            }
        }
    </div>
    <br />
    <form method="get" class="d-flex" style="width:50%">
        <label class="control-label">Name:&nbsp;</label>
        <input name="name" class="form-control" />
 
        <label class="control-label">&nbsp;Tag:&nbsp;</label>
        <input name="tag" class="form-control" />
 
        <input type="submit" value="Filter" class="btn btn-primary mx-2" />
    </form>
    <br />
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                <a asp-controller="Item" asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort">
                    Item name
                </a>                
            </th>
            <th>
                <a asp-controller="Item" asp-action="Index" asp-route-sortOrder="@ViewBag.TagSort">
                    Tag
                </a>
            </th>
            @if (GlobalCollection.FieldName != null && GlobalCollection.TypeField != null)
            {
                <th>
                    @GlobalCollection.FieldName
                </th>
            }
            @if (GlobalCollection.FieldName1 != null && GlobalCollection.TypeField1 != null)
            {
                <th>
                    @GlobalCollection.FieldName1
                </th>
            }
            @if (GlobalCollection.FieldName2 != null && GlobalCollection.TypeField2 != null)
            {
                <th>
                    @GlobalCollection.FieldName2
                </th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td>
                    @obj.Name
                </td>
                <td>
                    @obj.Tag
                </td>
                @if (GlobalCollection.FieldName != null && GlobalCollection.TypeField != null)
                {
                    switch (GlobalCollection.TypeField)
                    {
                        case FieldType.Numeric:
                            <td>
                                @obj.SpecialInt
                            </td>
                            break;
                        case FieldType.String:
                            <td>
                                @obj.SpecialString
                            </td>
                            break;
                        case FieldType.Text:
                            <td>
                                @obj.SpecialText
                            </td>    
                            break;
                        case FieldType.Date:
                            <td>
                                @obj.SpecialDataType
                            </td>
                            break;
                        case FieldType.TrueFalse:
                            <td>
                                @obj.SpecialBool
                            </td>
                            break;
                    }
                }
                @if (GlobalCollection.FieldName1 != null && GlobalCollection.TypeField1 != null)
                {
                    switch (GlobalCollection.TypeField1)
                    {
                        case FieldType.Numeric:
                            <td>
                                @obj.SpecialInt1
                            </td>
                            break;
                        case FieldType.String:
                            <td>
                                @obj.SpecialString1
                            </td>
                            break;
                        case FieldType.Text:
                            <td>
                                @obj.SpecialText1
                            </td>    
                            break;
                        case FieldType.Date:
                            <td>
                                @obj.SpecialDataType1
                            </td>
                            break;
                        case FieldType.TrueFalse:
                            <td>
                                @obj.SpecialBool1
                            </td>
                            break;
                    }
                }
                @if (GlobalCollection.FieldName2 != null && GlobalCollection.TypeField2 != null)
                {
                    switch (GlobalCollection.TypeField2)
                    {
                        case FieldType.Numeric:
                            <td>
                                @obj.SpecialInt2
                            </td>
                            break;
                        case FieldType.String:
                            <td>
                                @obj.SpecialString2
                            </td>
                            break;
                        case FieldType.Text:
                            <td>
                                @obj.SpecialText2
                            </td>    
                            break;
                        case FieldType.Date:
                            <td>
                                @obj.SpecialDataType2
                            </td>
                            break;
                        case FieldType.TrueFalse:
                            <td>
                                @obj.SpecialBool2
                            </td>
                            break;
                    }
                }
                <td width="10%">
                    <div class="w-100 btn-group" role="group">
                        <a asp-controller="Comment" asp-action="Index" asp-route-id="@obj.Id"
                        class="btn btn-primary mx-2">Details</a>
                    </div>
                </td>
                @if (obj.UserId == GlobalAppUserId.UserId || User.IsInRole("admin"))
                {
                    <td width="11%">
                        <div class="w-100 btn-group" role="group">
                            <a asp-controller="Item" asp-action="Edit" asp-route-id="@obj.Id"
                            class="btn btn-primary mx-2"> <i class="bi bi-pencil"> </i>Edit</a>
                        </div>
                    </td>
                    <td width="13%">
                        <div class="w-100 btn-group" role="group">
                            <a asp-controller="Item" asp-action="Del" asp-route-id="@obj.Id"
                            class="btn btn-danger mx-2"> <i class="bi bi-trash3"> </i>Delete</a>
                        </div> 
                    </td>
                }
            </tr>
        }
    </tbody>
</table>
</div>